version: "3.7"

services:
  db:
    image: postgres:latest
    hostname: postgres
    environment:
#      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_HOST}
    ports:
      - ${DB_PORT}:5432

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000
    depends_on:
      - db